//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descricao
    {
        public int Id { get; set; }
        public string Conferencia { get; set; }
        public Nullable<int> Campeonatos { get; set; }
        public string MVP { get; set; }
        public string Estadio { get; set; }
    
        public virtual Time Time { get; set; }
    }
}
